version: '3'

services:
  # rabbitmq:
  #   image: rabbitmq:latest
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   ports:
  #     - 5672:5672

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  # webserver:
  #   image: ahilanashwin/celery-fastapi
  #   env_file: &env
  #     - docker-compose.env
  #   depends_on: &deps
  #     - rabbitmq
  #     - redis
  #   ports:
  #     - 80:80
  #   command: ["uvicorn", "app.start:app", "--host", "0.0.0.0", "--port", "80"]

  # flower:
  #   image: mher/flower:latest
  #   ports:
  #     - "5555:5555"
  #   env_file: *env 
  #   depends_on: *deps

  # worker:
  #   image: ahilanashwin/celery-fastapi
  #   env_file: *env 
  #   depends_on: *deps
  #   command: ["celery", "--app", "app.celery_etl", "worker", "-l", "INFO"]