version: '3'

# Change password for fields using .envfile

services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  flower:
    image: mher/flower:latest
    ports:
      - "5555:5555"
    environment:
      CELERY_RESULT_BACKEND: redis://redis:6379
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - redis
